const currencies = {
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "DKK": "Danish Krone",
    "FJD": "Fiji Dollar",
    "HKD": "Hong Kong Dollar",
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "DKK": "Danish Krone",
    "FJD": "Fiji Dollar",
    "HKD": "Hong Kong Dollar",
    "INR": "Indian Rupee",
    "LKR": "Sri Lanka Rupee",
    "NOK": "Norwegian Krone",
    "PGK": "Papua New Guinea Kina",
    "PHP": "Philippine Peso",
    "SBD": "Solomon Islands Dollar",
    "SEK": "Swedish Krona",
    "SGD": "Singapore Dollar",
    "THB": "Thai Baht",
    "TOP": "Tonga Pa'anga",
    "VUV": "Vanuatu Vatu",
    "WST": "Samoa Tala",
    "XPF": "CFP Franc",
    "ZAR": "South African Rand",
};
