const currencies = {
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "DKK": "Danish Krone",
    "FJD": "Fiji Dollar",
    "HKD": "Hong Kong Dollar",
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "DKK": "Danish Krone",
    "FJD": "Fiji Dollar",
    "HKD": "Hong Kong Dollar",
    "INR": "Indian Rupee",
    "LKR": "Sri Lanka Rupee",
    "NOK": "Norwegian Krone",
    "PGK": "Papua New Guinea Kina",
    "PHP": "Philippine Peso",
};
