const currencies = {
    "AED": "United Arab Emirates",
    "AUD": "Australia",
    "BHD": "Bahrain",
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "CNY": "China",
    "DKK": "Danish Krone",
    "EUR": "Euro",
    "FJD": "Fiji Dollar",
    "GBP": "Great Britain",
    "HKD": "Hong Kong Dollar",
    "INR": "Indian Rupee",
    "JPY": "Japan",
    "KRW": "South Korea",
    "KWD": "Kuwait",
    "LKR": "Sri Lanka Rupee",
    "MYR": "Malaysia",
    "NOK": "Norwegian Krone",
    "PGK": "Papua New Guinea Kina",
    "PHP": "Philippine Peso",
    "PKR": "Pakistan",
    "SBD": "Solomon Islands Dollar",
    "SEK": "Swedish Krona",
    "SGD": "Singapore Dollar",
    "THB": "Thai Baht",
    "TOP": "Tonga Pa'anga",
    "USD": "United States",
    "VUV": "Vanuatu Vatu",
    "WST": "Samoa Tala",
    "XPF": "CFP Franc",
    "ZAR": "South African Rand",
};
